server:
  port: 6000

spring:
  application:
    name: gulimall-member

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gulimall-ums?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#
#mybatis-plus:
#  mapper-locations: classpath://mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto


gulimall:
  swagger:
    enable: true
    controller-package: com.tangtao.gulimall.member.controller